### PR TITLE
style(plugin-csl): update apa to 7th edition

### LINKED ISSUE #88: Bump built-in APA CSL for plugin-csl to 7th edition
The current [built-in APA CSL](https://github.com/citation-js/citation-js/blob/113776d8b373284f4484c33bfaf13bb78de146f0/packages/plugin-csl/src/styles.json) is for the 6th edition, which is out of date as of [October 2019](https://www.scribbr.com/apa-style/apa-seventh-edition-changes/). The new edition includes a number of very noticeable changes, like using et al. for inline citations after 2 authors instead of 5, formatting DOIs as URLs, removing "retrieved from" from URLs, etc.

There is an updated [7th Edition csl](https://github.com/citation-style-language/styles/blob/master/apa.csl), published by zotero, in the Citation Style Language github repo.

I'd be happy to submit a quick PR if you'd like, but wanted to make sure there wasn't some kind of reasoning for not doing so before that, because we could just manually add the APA 7th edition from the CSL repo if needed (also, it seems simple enough that it may not be worth it to have me submit).

### PR DESCRIPTION
**Pull request by gabestein**
Fixes #88 by updating the built-in APA style to use the 7th edition, from https://github.com/citation-style-language/styles/blob/master/apa.csl

I collapsed lines, stripped inter-carrot whitespace (`> <` --> `><`), and stripped comments. After that, I validated using the [CSL Validator](https://validator.citationstyles.org/). I then escaped all quotations (") and validated the resulting string in a JSON Validator. Finally, I ran `npm run test` and `npm run test:live`. There were a few configuration errors for core and wikidata, but the plugin-csl tests, which include export apa styles, all passed.

### CODE REVIEW

**Comment by larsgw** [comment]
I don't know why the CI results are not showing up, but the CI https://travis-ci.org/github/citation-js/citation-js/jobs/699768264 shows only test failures for the `plugin-csl` tests (which makes sense, the output changed). What configuration errors are you seeing?

**Comment by gabestein** [comment]
Whoops, of course I'll need to update the tests.

I was getting a number of cannot find module errors (`@babel/plugin-proposal-class-properties`, `@citation-js/core`). All I did before running is npm install...are there any other build steps I need to run before testing?

Also, wonder if it's a node version thing. I'm running 12.4.0 globally, but can change that to whichever is preferred (apologies if it's specified somewhere, didn't see a nodenv file or a version in the package).

**Comment by larsgw** [comment]
Those dependencies are managed with Lerna. There is a [`CONTRIBUTING.md`](https://github.com/citation-js/citation-js/blob/v0.5/CONTRIBUTING.md#installing) but only in the `v0.5` branch so not so visible yet :/

**Comment by gabestein** [comment]
Ah ok! Sorry I missed that. I'll have a look tomorrow, re-write the test, and update the PR!

**Comment by gabestein** [comment]
Apologies for some issues, but hopefully this is a good test of your new contrib guidelines, too.

I'm now getting the following when running `npm test` (after `lerna bootstrap`):

```
Error: Cannot find module '/Users/gabe/code/citation-js/packages/plugin-csl/node_modules/@citation-js/core/lib/index.js'. Please verify that the package.json has a valid "main" entry
```

**Comment by gabestein** [comment]
Thanks! Got the tests working. But now, I think I've found an issue with the CSL for the 7th edition that's coming up in tests, but it's such an edge case, I'm wondering how you want to proceed.

Long story short: when citing a journal article with [no author in a parenthetical](https://sfcollege.libguides.com/apa7/intext#:~:text=If%20there%20is%20truly%20no,is%20an%20article%20or%20chapter.), you use the title, in headline case, surrounded by quotes, followed by the date, e.g.: 

> ("This Is My Article," 2020)

The test was not expecting headline case, which I think was an error with the 6th edition CSL that was being used. I've updated the test. But the new 7th edition CSL doesn't surround the title with quotations, which is technically wrong, e.g.:

> (This Is My Article, 2020)

I'm pretty new to CSL. I updated what I think is the right definition, and the tests now pass (see the latest commit). But there may be side-effects I don't understand. I'm happy to submit a PR against the CSL repo. But in the meantime, if you feel confident enough to move forward, it's ready to go. Or, if this seems like a tiny edge case, I can revert back to the old CSL and update the test to not expect quotes, even though it's technically correct.

**Comment by larsgw** [comment]
The entry type was changed to `website`, maybe that's the problem?

**Comment by gabestein** [comment]
Ah, sorry, I changed that to see if it was a type issue or not. It's the same whether it's a `website` or `journal-article`. Just changed it back.

**Comment by larsgw** [comment]
Isn't it correct now though? I get

> (“How To Find,” 2009)

with

```js
{
  type: 'article-journal',
  title: 'How To Find',
  issued: { 'date-parts': [[2009]] }
}
```

**Comment by gabestein** [comment]
Yes. But, it's because I made a manual update to the CSL XML in the place where I think the error was. But not being super familiar with CSL, I want to make sure that doesn't introduce any side effects. I've copied the changed line below (hard to point to the specific line in the file since it's all one line.

```<macro name=\"title-intext\"><choose><if variable=\"title\" match=\"none\"><text macro=\"bracketed-intext\" prefix=\"[\" suffix=\"]\"/></if><else-if type=\"bill\"><choose><if variable=\"number container-title\" match=\"none\"><text variable=\"title\" form=\"short\" font-style=\"italic\" text-case=\"title\"/></if><else-if variable=\"title\"><text variable=\"title\" form=\"short\" text-case=\"title\"/></else-if><else><group delimiter=\" \"><text variable=\"genre\"/><group delimiter=\" \"><choose><if variable=\"chapter-number container-title\" match=\"none\"><text term=\"issue\" form=\"short\"/></if></choose><text variable=\"number\"/></group></group></else></choose></else-if><else-if type=\"legal_case\" match=\"any\"><text variable=\"title\" font-style=\"italic\"/></else-if><else-if type=\"legislation treaty\" match=\"any\"><text variable=\"title\" form=\"short\" text-case=\"title\"/></else-if><else-if type=\"post webpage\" match=\"any\"><text variable=\"title\" form=\"short\" font-style=\"italic\" text-case=\"title\"/></else-if><else-if variable=\"container-title\" match=\"any\"><text variable=\"title\" form=\"short\" quotes=\"true\" text-case=\"title\"/></else-if><else><text variable=\"title\" form=\"short\" font-style=\"italic\" text-case=\"title\" quotes=\"true\"/></else></choose></macro>```

Specifically, added `quotes="true"` here:

```<else><text variable=\"title\" form=\"short\" font-style=\"italic\" text-case=\"title\" quotes=\"true\"/></else>```

**Comment by larsgw** [comment]
Ah. In that case, @bwiernik?

**Comment by bwiernik** [comment]
The use of quotes versus italics in text is based on the presence of a container title: https://github.com/citation-style-language/styles/blob/c66a5c00d94e462644a3f01bc2d2b7d0b82b285c/apa.csl#L698

Items with a container title (e.g., articles, chapter, etc.; except for web pages and blog posts) are in quotes. Items without a container title are in italics. The example @gabestein must not have had a container-title in the data.

(I'd ask to please not change the CSL code used for APA in citation.js. It's a fair amount of work keeping the versions of apa.csl up to date, and I'd like to be sure that we don't have different out of sync versions floating around in different projects.)

**Comment by bwiernik** [comment]
> `<else><text variable=\"title\" form=\"short\" font-style=\"italic\" text-case=\"title\" quotes=\"true\"/></else>`

No, this is incorrect. In-text titles should be either in italics or have quotes, not both.

**Comment by gabestein** [comment]
Ah, ok, thanks @bwiernik. That's why I asked.

I'll revert to the canonical version of apa.csl, which is what I had before, and change the test to not expect quotations. I'll also try a test with an object with a container title.

**Comment by larsgw** [comment]
Ah, that's the reason. Thanks!

**Comment by gabestein** [comment]
Ok! I tested it locally with a container title and it works, but that didn't really seem core to the testing you're doing there. So, I reverted the csl back to the original and changed the test to not expect quotes. If you want me to add a test for an entry with a container title, let me know, happy to. But otherwise, I think this is good to go. Apologies for the back and forth here and the deep dive into the depths of edge-case APA style and CSL.

**Comment by bwiernik** [comment]
@gabestein Let me know if you ever want to trade war stories of APA edge cases; I know that book in way too much detail at this point 😜

**Comment by gabestein** [comment]
@bwiernik I can't imagine! This is actually my first one, as I'm relatively new to the CSL world. But we're doing a little work with APA on PubPub, which is how I noticed this, so it'll probably be the first of many. In any case, I'll send you a note offline!

**Pull request merged**
